version: "3.8"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000" # Maps port 5000 on the host to port 5000 in the container
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongodb:27017/second-test-assignment
      - JWT_SECRET=some_secrect_key
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_API_URL=backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: # enable persistence of database data across container restart
  mongo-data:
    driver: local
